/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M9
 * Generated at: 2019-12-18 04:52:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CrossGame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>사다리 게임</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var n;\r\n");
      out.write("var point = -50;\r\n");
      out.write("var Yl = {\r\n");
      out.write(" getEl : function(strId){\r\n");
      out.write("  if (document.getElementById) return document.getElementById(strId);\r\n");
      out.write("  if (document.all) return document.all[strId];\r\n");
      out.write(" }\r\n");
      out.write(" //div 리턴\r\n");
      out.write(" ,getDiv : function(sWidth, sHeight, sBgColor){\r\n");
      out.write("  var d = document.createElement(\"div\");\r\n");
      out.write("  if(sWidth) d.style.width = sWidth;\r\n");
      out.write("  if(sHeight) d.style.height = sHeight;\r\n");
      out.write("  if(sBgColor) d.style.backgroundColor = sBgColor;\r\n");
      out.write("  d.style.position = \"absolute\";\r\n");
      out.write("  d.style.overflow = \"hidden\";\r\n");
      out.write("  return d;\r\n");
      out.write(" }\r\n");
      out.write(" ,arrColor : [\r\n");
      out.write("  '#8c7301','#9b014f','#0084a0','#ad8e00','#bb005f'\r\n");
      out.write("  ,'#00a0c2','#8d3901','#8f0197','#156200','#9ca53b'\r\n");
      out.write("  ,'#c9a601','#d6006d','#01b6de','#80adaf','#a44201'\r\n");
      out.write("  ,'#e0b800','#ec0078','#0021b0','#92b7d7','#013add'\r\n");
      out.write("  ]\r\n");
      out.write(" ,arrVerDiv : [] //수직 선 div\r\n");
      out.write(" ,arrHorDiv : [] //수평 선 div\r\n");
      out.write(" ,arrMovDiv : [] //이동 선 div\r\n");
      out.write("\r\n");
      out.write(" ,arrIng : [] //진행여부 체크용\r\n");
      out.write("\r\n");
      out.write(" ,arrMDiv : [] //이동선 배열 번호값 저장, 이동후 확인용\r\n");
      out.write("\r\n");
      out.write(" ,nMaxWidth : 1000 //최고 넓이\r\n");
      out.write(" ,nWidth : 0 //사다리 넓이\r\n");
      out.write(" ,nHeight : 300 //사다리 높이\r\n");
      out.write("\r\n");
      out.write(" ,nNum : 0\r\n");
      out.write("\r\n");
      out.write(" ,arrTopDiv : [] //탑 div\r\n");
      out.write(" ,arrBotDiv : [] //아래 div\r\n");
      out.write(" ,arrGoDiv : [] //go 버튼 div\r\n");
      out.write("\r\n");
      out.write(" ,init : function(){\r\n");
      out.write("\r\n");
      out.write("  //갯수\r\n");
      out.write("  this.nNum = parseInt(this.getEl(\"sel_num\").value);\r\n");
      out.write("\r\n");
      out.write("  //넓이\r\n");
      out.write("  this.nWidth = parseInt(this.nMaxWidth/this.nNum);\r\n");
      out.write("\r\n");
      out.write("  for(var i=0; i<this.nNum; i++){\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i] = this.getDiv(this.nWidth+\"px\", \"50px\", \"\");\r\n");
      out.write("   this.arrBotDiv[i] = this.getDiv(this.nWidth+\"px\", \"50px\", \"\");\r\n");
      out.write("   this.arrGoDiv[i] = this.getDiv(this.nWidth+\"px\", \"30px\", \"\");\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].style.left = (i*this.nWidth)+\"px\";\r\n");
      out.write("   this.arrTopDiv[i].style.top = \"20px\";\r\n");
      out.write("\r\n");
      out.write("   this.arrBotDiv[i].style.left = (i*this.nWidth)+\"px\";\r\n");
      out.write("   this.arrBotDiv[i].style.top = \"410px\";\r\n");
      out.write("\r\n");
      out.write("   this.arrGoDiv[i].style.left = (i*this.nWidth)+\"px\";\r\n");
      out.write("   this.arrGoDiv[i].style.top = \"70px\";\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].style.fontSize=\"12px\";\r\n");
      out.write("   this.arrBotDiv[i].style.fontSize=\"12px\";\r\n");
      out.write("\r\n");
      out.write("   //this.arrTopDiv[i].style.border = \"1px solid #CCCCCC\";\r\n");
      out.write("   //this.arrBotDiv[i].style.border = \"1px solid #CCCCCC\";\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].align = \"center\";\r\n");
      out.write("   this.arrBotDiv[i].align = \"center\";\r\n");
      out.write("   this.arrGoDiv[i].align = \"center\";\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].innerHTML = (i+1) + '<p><input type=\"button\" value=\"시작\" id=\"inp_top_'+i+'\"class=\"btn btn-success\" onclick=\"Yl.create('+i+');\">'/*+'<br><input type=\"text\" id=\"inp_top_'+i+'\" value=\"\" style=\"width:90%\" tabindex=\"'+(i+1)+'\" />'*/;\r\n");
      out.write("   if(i!=this.nNum-1){\r\n");
      out.write("\t   this.arrBotDiv[i].innerHTML = '<input type=\"text\" id=\"inp_bot_'+i+'\" value=\"꽝\" style=\"width:90%\" tabindex=\"'+((i+1)+50)+'\" />';\r\n");
      out.write("   }else{\r\n");
      out.write("\t   this.arrBotDiv[i].innerHTML = '<input type=\"text\" id=\"inp_bot_'+i+'\" value=\"당첨\" style=\"width:90%\" tabindex=\"'+((i+1)+50)+'\" />';\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   this.getEl(\"div_body\").appendChild(this.arrTopDiv[i]);\r\n");
      out.write("   this.getEl(\"div_body\").appendChild(this.arrBotDiv[i]);\r\n");
      out.write("   this.getEl(\"div_body\").appendChild(this.arrGoDiv[i]);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   this.arrVerDiv[i] = this.getDiv(\"1px\", this.nHeight+\"px\", \"#bbbbbb\");\r\n");
      out.write("\r\n");
      out.write("   this.arrVerDiv[i].style.left = ( (i*this.nWidth)+parseInt(this.nWidth/2) )+\"px\";\r\n");
      out.write("   this.arrVerDiv[i].style.top = \"100px\";\r\n");
      out.write("\r\n");
      out.write("   this.getEl(\"div_body\").appendChild(this.arrVerDiv[i]);\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  this.getEl(\"div_step1\").style.display = \"none\";\r\n");
      out.write("  this.getEl(\"div_step2\").style.display = \"\";\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" ,create : function(tn){ //사다리 생성\r\n");
      out.write("\t n = tn;\r\n");
      out.write("  for(var i=0; i<this.nNum; i++){\r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].innerHTML = (i+1);\r\n");
      out.write("   this.arrBotDiv[i].innerHTML = this.getEl(\"inp_bot_\"+i).value;\r\n");
      out.write("   if(n==i){\r\n");
      out.write("\t   this.arrGoDiv[i].innerHTML = '<input type=\"button\" class=\"btn btn-success\" value=\"GO\" onClick=\"Yl.start('+i+')\">';   \r\n");
      out.write("   }  \r\n");
      out.write("\r\n");
      out.write("   this.arrTopDiv[i].style.overflow = \"auto\";\r\n");
      out.write("   this.arrBotDiv[i].style.overflow = \"auto\";\r\n");
      out.write("\r\n");
      out.write("   this.arrIng[i] = false;\r\n");
      out.write("\r\n");
      out.write("   this.arrMDiv[i] = [];\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  for(var i=0; i<(this.nNum*7); i++){\r\n");
      out.write("\r\n");
      out.write("   var nLen = this.arrHorDiv.length;\r\n");
      out.write("\r\n");
      out.write("   this.arrHorDiv[nLen] = this.getDiv(this.nWidth+\"px\",\"1px\", \"#aaaaaa\");\r\n");
      out.write("\r\n");
      out.write("   var nRndLeft = (parseInt(Math.random()*(this.nNum-1))*this.nWidth)+parseInt(this.nWidth/2);\r\n");
      out.write("   var nRndTop = this.getRndTop();\r\n");
      out.write("\r\n");
      out.write("   this.arrHorDiv[nLen].style.left = nRndLeft+\"px\";\r\n");
      out.write("   this.arrHorDiv[nLen].style.top = nRndTop+\"px\";\r\n");
      out.write("\r\n");
      out.write("   this.getEl(\"div_body\").appendChild(this.arrHorDiv[nLen]);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  //this.getEl(\"div_step2\").innerHTML = \"<center>\" + '<a href=\"PointChangeSave.jsp?_point='+point+'&_type=game\">포인트 집계 확인</a></center>';\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" ,sRndTop : \"\"\r\n");
      out.write(" ,getRndTop : function(){\r\n");
      out.write("  var nRnd = parseInt(Math.random()*(this.nHeight-100))+150;\r\n");
      out.write("\r\n");
      out.write("  if( this.sRndTop.indexOf( \"[\"+nRnd+\"]\" ) < 0 ){\r\n");
      out.write("   this.sRndTop += \"[\"+nRnd+\"]\";\r\n");
      out.write("   return nRnd;\r\n");
      out.write("  }else{\r\n");
      out.write("   return this.getRndTop();\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write(" ,start : function( no ){\r\n");
      out.write("\r\n");
      out.write("  if( this.arrIng[no] ){\r\n");
      out.write("   for(var i=0; i<this.arrMDiv.length; i++){\r\n");
      out.write("    for(var j=0; j<this.arrMDiv[i].length; j++){\r\n");
      out.write("     this.arrMovDiv[this.arrMDiv[i][j]].style.backgroundColor = \"#CCCCCC\";\r\n");
      out.write("     this.arrMovDiv[this.arrMDiv[i][j]].style.zIndex = 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("   for(var i=0; i<this.arrMDiv[no].length; i++){\r\n");
      out.write("    this.arrMovDiv[this.arrMDiv[no][i]].style.backgroundColor = \"#0000ff\";\r\n");
      out.write("    this.arrMovDiv[this.arrMDiv[no][i]].style.zIndex = 2;\r\n");
      out.write("   }\r\n");
      out.write("  }else{\r\n");
      out.write("\r\n");
      out.write("   var nSx = parseInt(this.arrVerDiv[no].style.left);\r\n");
      out.write("   var nSy = parseInt(this.arrVerDiv[no].style.top);\r\n");
      out.write("\r\n");
      out.write("   this.moveStart(\"y\", no, nSx, nSy);\r\n");
      out.write("\r\n");
      out.write("   this.arrIng[no] = true; //진행\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write(" ,moveStart : function(sXy, pno, nSx, nSy){\r\n");
      out.write("\r\n");
      out.write("  var nLen = this.arrMovDiv.length;\r\n");
      out.write("\r\n");
      out.write("  this.arrMovDiv[nLen] = this.getDiv(\"2px\",\"2px\", this.arrColor[pno]);\r\n");
      out.write("\r\n");
      out.write("  this.arrMDiv[pno].push(nLen);\r\n");
      out.write("\r\n");
      out.write("  this.getEl(\"div_body\").appendChild(this.arrMovDiv[nLen]);\r\n");
      out.write("\r\n");
      out.write("  this.arrMovDiv[nLen].style.left = nSx+\"px\";\r\n");
      out.write("  this.arrMovDiv[nLen].style.top = nSy+\"px\";\r\n");
      out.write("\r\n");
      out.write("  this.arrMovDiv[nLen].style.zIndex = 3;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  var nEx = nSx;\r\n");
      out.write("  var nEy = nSy;\r\n");
      out.write("  if(sXy==\"y\") nEy = this.nHeight+100;\r\n");
      out.write("\r\n");
      out.write("  var bCk = false;\r\n");
      out.write("\r\n");
      out.write("  for(var i=0; i<this.arrHorDiv.length; i++){\r\n");
      out.write("\r\n");
      out.write("   var nx = parseInt(this.arrHorDiv[i].style.left);\r\n");
      out.write("   var ny = parseInt(this.arrHorDiv[i].style.top);\r\n");
      out.write("   var nw = parseInt(this.arrHorDiv[i].style.width);\r\n");
      out.write("   var nh = parseInt(this.arrHorDiv[i].style.height);\r\n");
      out.write("\r\n");
      out.write("   if(sXy==\"x\"){\r\n");
      out.write("    if( ny == nSy ){\r\n");
      out.write("     if( nx==nSx ){\r\n");
      out.write("      nEx = nx+nw;\r\n");
      out.write("      break;\r\n");
      out.write("     }else if( (nx+nw)==nSx ){\r\n");
      out.write("      nEx = nx;\r\n");
      out.write("      break;\r\n");
      out.write("     }\r\n");
      out.write("    }\r\n");
      out.write("   }else{\r\n");
      out.write("\r\n");
      out.write("    //반복하면서 큰것중에서 제일 작은것으로\r\n");
      out.write("    if( ny>nSy ){\r\n");
      out.write("\r\n");
      out.write("     if( nx==nEx || (nx+nw)==nEx ){\r\n");
      out.write("\r\n");
      out.write("      if(bCk){\r\n");
      out.write("       if(ny<nEy) nEy = ny;\r\n");
      out.write("      }else\r\n");
      out.write("       nEy = ny;\r\n");
      out.write("\r\n");
      out.write("      bCk = true;\r\n");
      out.write("     }\r\n");
      out.write("    }\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  this.move(nLen, pno, nSx, nSy, nEx, nEy);\r\n");
      out.write(" }\r\n");
      out.write(" ,nSpeed : 10\r\n");
      out.write(" ,move : function(no, pno, nSx, nSy, nEx, nEy){\r\n");
      out.write("\r\n");
      out.write("  var nx = parseInt(this.arrMovDiv[no].style.left);\r\n");
      out.write("  var ny = parseInt(this.arrMovDiv[no].style.top);\r\n");
      out.write("  var nw = parseInt(this.arrMovDiv[no].style.width);\r\n");
      out.write("  var nh = parseInt(this.arrMovDiv[no].style.height);\r\n");
      out.write("\r\n");
      out.write("  var np;\r\n");
      out.write("  var bIng = true;\r\n");
      out.write("\r\n");
      out.write("  var sXy = \"\";\r\n");
      out.write("\r\n");
      out.write("  if( nSx != nEx ){\r\n");
      out.write("   np = nw+this.nSpeed;\r\n");
      out.write("   if(nEx<nSx){\r\n");
      out.write("    if( (nSx-np) <= nEx ){\r\n");
      out.write("     bIng = false;\r\n");
      out.write("     np = nSx-nEx;\r\n");
      out.write("    }\r\n");
      out.write("    this.arrMovDiv[no].style.left = (nSx-np)+\"px\";\r\n");
      out.write("   }else{\r\n");
      out.write("    if( (nSx+np) >= nEx ){\r\n");
      out.write("     bIng = false;\r\n");
      out.write("     np = nEx-nSx;\r\n");
      out.write("    }\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   this.arrMovDiv[no].style.height = \"4px\";\r\n");
      out.write("   this.arrMovDiv[no].style.width = np+\"px\";\r\n");
      out.write("\r\n");
      out.write("   sXy = \"x\";\r\n");
      out.write("  }else{\r\n");
      out.write("\r\n");
      out.write("   np = nh+this.nSpeed;\r\n");
      out.write("   if( (nSy+np) >= nEy ){\r\n");
      out.write("    bIng = false;\r\n");
      out.write("    np = nEy-nSy;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   this.arrMovDiv[no].style.width = \"4px\";\r\n");
      out.write("   this.arrMovDiv[no].style.height = np+\"px\";\r\n");
      out.write("\r\n");
      out.write("   sXy = \"y\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  if(bIng){\r\n");
      out.write("\r\n");
      out.write("   setTimeout(\"Yl.move(\"+no+\",\"+pno+\",\"+nSx+\",\"+nSy+\",\"+nEx+\",\"+nEy+\")\", 1);\r\n");
      out.write("\r\n");
      out.write("  }else{\r\n");
      out.write("\r\n");
      out.write("   if((sXy==\"x\")) this.arrMovDiv[no].style.height = \"2px\";\r\n");
      out.write("   else this.arrMovDiv[no].style.width = \"2px\";\r\n");
      out.write("\r\n");
      out.write("   if( nEy<this.nHeight+100 ){\r\n");
      out.write("    this.moveStart((sXy==\"x\")?\"y\":\"x\", pno, nEx, nEy);\r\n");
      out.write("   }else{\r\n");
      out.write("\r\n");
      out.write("    for(var i=0; i<this.arrVerDiv.length; i++){\r\n");
      out.write("     if(nEx==parseInt(this.arrVerDiv[i].style.left)){\r\n");
      out.write("    \t if(i!=this.arrVerDiv.length-1){\r\n");
      out.write("    \t\t this.arrBotDiv[i].innerHTML = \"<b>\"+(pno+1)+\"</b><br>\"+this.arrBotDiv[i].innerHTML;\r\n");
      out.write("    \t }else{\r\n");
      out.write("    \t\t this.arrBotDiv[i].innerHTML = \"<b>\"+(pno+1)+\"</b><br>\"+this.arrBotDiv[i].innerHTML;\r\n");
      out.write("    \t\t if(pno==n){\r\n");
      out.write("    \t\t\t point = 50;\r\n");
      out.write("    \t\t }\r\n");
      out.write("    \t }\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      this.arrGoDiv[pno].innerHTML = '<a href=\"PointChangeSave.jsp?_point='+point+'&_type=game\">포인트 집계 확인</a></center>';\r\n");
      out.write("\r\n");
      out.write("      break;\r\n");
      out.write("     }\r\n");
      out.write("    }\r\n");
      out.write("   }\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("//F5 새로고침 막기\r\n");
      out.write("document.onkeydown = function(e){\r\n");
      out.write(" if(!e) e = window.event;\r\n");
      out.write(" if (e.keyCode == 116){\r\n");
      out.write("  if( confirm(\"새로 고침 하시겠습니까?\") ){\r\n");
      out.write("  }else{\r\n");
      out.write("   e.keyCode = 0;\r\n");
      out.write("   return false;\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

String id = (String)session.getAttribute("__id");
if(id==null){
	id = "ID101";
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"div_step1\" style=\"font-size:12px;\">\r\n");
      out.write("\r\n");
      out.write("갯수 선택\r\n");
      out.write("<select id=\"sel_num\">\r\n");
      out.write(" <option value=\"2\">2</option>\r\n");
      out.write(" <option value=\"3\">3</option>\r\n");
      out.write(" <option value=\"4\">4</option>\r\n");
      out.write(" <option value=\"5\" selected >5</option>\r\n");
      out.write(" <option value=\"6\">6</option>\r\n");
      out.write(" <option value=\"7\">7</option>\r\n");
      out.write(" <option value=\"8\">8</option>\r\n");
      out.write(" <option value=\"9\">9</option>\r\n");
      out.write(" <option value=\"10\">10</option>\r\n");
      out.write(" <option value=\"11\">11</option>\r\n");
      out.write(" <option value=\"12\">12</option>\r\n");
      out.write(" <option value=\"13\">13</option>\r\n");
      out.write(" <option value=\"14\">14</option>\r\n");
      out.write(" <option value=\"15\">15</option>\r\n");
      out.write(" <option value=\"16\">16</option>\r\n");
      out.write(" <option value=\"17\">17</option>\r\n");
      out.write(" <option value=\"18\">18</option>\r\n");
      out.write(" <option value=\"19\">19</option>\r\n");
      out.write(" <option value=\"20\">20</option>\r\n");
      out.write("</select>\r\n");
      out.write("개\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" class=\"btn btn-success\" value=\"만들기\" onclick=\"Yl.init();\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"div_step2\" style=\"font-size:12px;display:none;\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"div_body\" style=\"width:1000px;height:450px;border:1px solid #CCCCCC;position:relative;\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
