/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M9
 * Generated at: 2019-12-18 04:28:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <link rel= \"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>먹튀 검증</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"container\">\r\n");

String id = (String)session.getAttribute("__id");
if(id!=null){
   response.sendRedirect("Main.jsp");
}

      out.write("\r\n");
      out.write("<form action=\"JoinCheck.jsp\" method=\"post\" onsubmit=\"return Check()\">    \r\n");
      out.write("  <div id=\"login\" class=\"Join\">\r\n");
      out.write("    <div>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t   <h1 class=\"h1style\"align=\"center\">Sign Up</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("      <div>\r\n");
      out.write("       <label >\r\n");
      out.write("        <svg version=\"1.1\" class=\"user-icon\" x=\"0px\" y=\"0px\"\r\n");
      out.write("        viewBox=\"-255 347 100 100\" xml:space=\"preserve\" height=\"36px\" width=\"30px\">\r\n");
      out.write("          <path class=\"user-path\" d=\"\r\n");
      out.write("          M-203.7,350.3c-6.8,0-12.4,6.2-12.4,13.8c0,4.5,2.4,8.6,5.4,11.1c0,0,2.2,1.6,1.9,3.7c-0.2,1.3-1.7,2.8-2.4,2.8c-0.7,0-6.2,0-6.2,0\r\n");
      out.write("          c-6.8,0-12.3,5.6-12.3,12.3v2.9v14.6c0,0.8,0.7,1.5,1.5,1.5h10.5h1h13.1h13.1h1h10.6c0.8,0,1.5-0.7,1.5-1.5v-14.6v-2.9\r\n");
      out.write("          c0-6.8-5.6-12.3-12.3-12.3c0,0-5.5,0-6.2,0c-0.8,0-2.3-1.6-2.4-2.8c-0.4-2.1,1.9-3.7,1.9-3.7c2.9-2.5,5.4-6.5,5.4-11.1\r\n");
      out.write("          C-191.3,356.5-196.9,350.3-203.7,350.3L-203.7,350.3z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"text\" name=\"_id\" placeholder=\"아이디 입력\"class=\"inputcolor\"></input>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div >\r\n");
      out.write("        <label>\r\n");
      out.write("        <svg version=\"1.1\" class=\"password-icon\" x=\"0px\" y=\"0px\"\r\n");
      out.write("        viewBox=\"-255 347 100 100\" height=\"36px\" width=\"30px\">\r\n");
      out.write("          <path class=\"key-path\" d=\"M-191.5,347.8c-11.9,0-21.6,9.7-21.6,21.6c0,4,1.1,7.8,3.1,11.1l-26.5,26.2l-0.9,10h10.6l3.8-5.7l6.1-1.1\r\n");
      out.write("          l1.6-6.7l7.1-0.3l0.6-7.2l7.2-6.6c2.8,1.3,5.8,2,9.1,2c11.9,0,21.6-9.7,21.6-21.6C-169.9,357.4-179.6,347.8-191.5,347.8z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"password\" name=\"_pw\" id=\"_pw\" placeholder=\"비밀번호 입력\"class=\"inputcolor\"></input>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <label >\r\n");
      out.write("        <svg version=\"1.1\" class=\"password-icon\" x=\"0px\" y=\"0px\"\r\n");
      out.write("        viewBox=\"-255 347 100 100\" height=\"36px\" width=\"30px\">\r\n");
      out.write("          <path class=\"key-path\" d=\"M-191.5,347.8c-11.9,0-21.6,9.7-21.6,21.6c0,4,1.1,7.8,3.1,11.1l-26.5,26.2l-0.9,10h10.6l3.8-5.7l6.1-1.1\r\n");
      out.write("          l1.6-6.7l7.1-0.3l0.6-7.2l7.2-6.6c2.8,1.3,5.8,2,9.1,2c11.9,0,21.6-9.7,21.6-21.6C-169.9,357.4-179.6,347.8-191.5,347.8z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"password\" name=\"_checkpw\" id=\"_checkpw\" placeholder=\"비밀번호 확인\"class=\"inputcolor\"></input>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <label >\r\n");
      out.write("        <svg version=\"1.1\" class=\"user-icon\" x=\"0px\" y=\"0px\"\r\n");
      out.write("        viewBox=\"-255 347 100 100\" xml:space=\"preserve\" height=\"36px\" width=\"30px\">\r\n");
      out.write("          <path class=\"user-path\" d=\"\r\n");
      out.write("          M-203.7,350.3c-6.8,0-12.4,6.2-12.4,13.8c0,4.5,2.4,8.6,5.4,11.1c0,0,2.2,1.6,1.9,3.7c-0.2,1.3-1.7,2.8-2.4,2.8c-0.7,0-6.2,0-6.2,0\r\n");
      out.write("          c-6.8,0-12.3,5.6-12.3,12.3v2.9v14.6c0,0.8,0.7,1.5,1.5,1.5h10.5h1h13.1h13.1h1h10.6c0.8,0,1.5-0.7,1.5-1.5v-14.6v-2.9\r\n");
      out.write("          c0-6.8-5.6-12.3-12.3-12.3c0,0-5.5,0-6.2,0c-0.8,0-2.3-1.6-2.4-2.8c-0.4-2.1,1.9-3.7,1.9-3.7c2.9-2.5,5.4-6.5,5.4-11.1\r\n");
      out.write("          C-191.3,356.5-196.9,350.3-203.7,350.3L-203.7,350.3z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"text\" name=\"_name\" placeholder=\"성명\"class=\"inputcolor\"></input>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <label >\r\n");
      out.write("        <svg version=\"1.1\" class=\"user-icon\" x=\"0px\" y=\"0px\"\r\n");
      out.write("        viewBox=\"-255 347 100 100\" xml:space=\"preserve\" height=\"36px\" width=\"30px\">\r\n");
      out.write("          <path class=\"user-path\" d=\"\r\n");
      out.write("          M-203.7,350.3c-6.8,0-12.4,6.2-12.4,13.8c0,4.5,2.4,8.6,5.4,11.1c0,0,2.2,1.6,1.9,3.7c-0.2,1.3-1.7,2.8-2.4,2.8c-0.7,0-6.2,0-6.2,0\r\n");
      out.write("          c-6.8,0-12.3,5.6-12.3,12.3v2.9v14.6c0,0.8,0.7,1.5,1.5,1.5h10.5h1h13.1h13.1h1h10.6c0.8,0,1.5-0.7,1.5-1.5v-14.6v-2.9\r\n");
      out.write("          c0-6.8-5.6-12.3-12.3-12.3c0,0-5.5,0-6.2,0c-0.8,0-2.3-1.6-2.4-2.8c-0.4-2.1,1.9-3.7,1.9-3.7c2.9-2.5,5.4-6.5,5.4-11.1\r\n");
      out.write("          C-191.3,356.5-196.9,350.3-203.7,350.3L-203.7,350.3z\"/>\r\n");
      out.write("        </svg>\r\n");
      out.write("        </label>\r\n");
      out.write("        <input type=\"text\" name=\"_phone\" placeholder=\"전화번호\"class=\"inputcolor\"></input>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"call-to-action\">\r\n");
      out.write("      <button id=\"JoinButton\" type=\"submit\" onclick=\"Check()\">회원가입</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>      \r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("      function Check() {\r\n");
      out.write("          var pw1 = document.getElementById(\"_pw\").value;\r\n");
      out.write("          var pw2 = document.getElementById(\"_checkpw\").value;\r\n");
      out.write("         if (pw1 == pw2) {\r\n");
      out.write("            return true;\r\n");
      out.write("         } else {\r\n");
      out.write("             alert('비밀번호를 확인해주세요.');\r\n");
      out.write("            return false;\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
